# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:        
        Sunu\UserBundle\Entity\User: sha512


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded*

    providers:
    # Et voici notre nouveau fournisseur :
        main:
            id: fos_user.user_provider.username

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        # On crée un pare-feu uniquement pour le formulaire
        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)  # On autorise alors les anonymes sur ce pare-feu
            pattern:   ^/(login$|register|resetting|platform|inscriptionconfirm)
            # Les adresses de ces pages sont login, register et resetting
            anonymous: true   
            # On autorise bien évidemment les anonymes sur ces pages !
          
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /accueil
            logout:
                invalidate_session: false
                path:    fos_user_security_logout
                target: /login
                # ici c'est le login de FOSUB
            remember_me:
                secret:     "%secret%"
                # %secret% est un paramètre de parameter 


        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
            