<?php

namespace Sunu\UserBundle\Repository;

/**
 * TypeCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
